import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {toast} from 'react-toastify'
import { axiosPrivate } from "@/api/axios";
import createAuthApi from "@/services/authApi";
const authApi = createAuthApi(axiosPrivate);
import DashboardSidebar from "@/components/admin/DashboardSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FixMyRide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
  <>
   <DashboardSidebar/>
   
        {children}
        
    <ToastContainer position="top-right" autoClose={3000} />

     </>  
     
   
  );
}
